# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d67735a002f51f955790758ac384de71041d5115030139df1a840c94b943531da7ba061187530971c8f934f47db6ec5e3e7f267e522792f0bef68df1aa675976

test:
  secret_key_base: bd6bf8b5f0f3aed1f9ce70cb53990184ed8a2220666d237c7f4611115b9250a3576930b7cb32ead441d1600372540523f460f9882a2f0fa5818de4dd27f22939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
